<a href="https://colab.research.google.com/github/sam-aiden/ChatBots/blob/main/Rule_based_Bot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random as rd

responses = {
    'hi':['hello','how can i help u?'],
    'how are you':['i am fine','im good','good thanks for asking'],
    'your name':['im just a bot','im your friendly chatbot'],
    'thank you':['you\'re welcome','don\'t mention']

}

def response(user_input):
  user_input = user_input.lower()
  if user_input in responses:
    return rd.choice(responses[user_input])
  else:
    return 'i dont understand'

while True:
  user_input = input('you: ')
  if user_input == 'bye':
    print('bot: bye')
    break
  print('bot: ',response(user_input))

you: bye
bot: bye


In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# Load the CSV file into a pandas DataFrame
data = pd.read_csv('saviour.csv')

# Select the relevant attributes for analysis
attributes = ['Age', 'Gender', 'Country', 'MentalHealthDisorder', 'TreatmentSeeking']

# Remove rows with missing values
data = data.dropna(subset=attributes)

# Convert categorical variables to numerical values
data['Gender'] = data['Gender'].astype('category').cat.codes
data['Country'] = data['Country'].astype('category').cat.codes
data['MentalHealthDisorder'] = data['MentalHealthDisorder'].astype('category').cat.codes
data['TreatmentSeeking'] = data['TreatmentSeeking'].astype('category').cat.codes

# Split the data into training and testing sets
X = data[['Age', 'Gender', 'Country', 'MentalHealthDisorder']]
y = data['TreatmentSeeking']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the Decision Tree Classifier
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = clf.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Create a confusion matrix to visualize the performance of the model
confusion_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(confusion_matrix)

KeyError: ignored

In [ ]:
import pandas as pd

# Specify the path to the XLS file you want to convert
xls_file_path = '/content/saviour 1.xlsx'

# Specify the path where you want to save the CSV file
csv_file_path = '/content/saviour1.csv'

# Use pandas to read the XLS file and then save it as a CSV
try:
    df = pd.read_excel(xls_file_path)
    df.to_csv(csv_file_path, index=False)  # Set index to False to exclude row numbers
    print(f'Successfully converted {xls_file_path} to {csv_file_path}')
except Exception as e:
    print(f'An error occurred: {e}')


Successfully converted /content/saviour 1.xlsx to /content/saviour1.csv


In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# Load the CSV file into a pandas DataFrame
data = pd.read_csv('saviour1.csv')

# Select the relevant attributes for analysis
attributes = ['Age', 'Gender', 'Country', 'MentalHealthDisorder', 'TreatmentSeeking']



# Convert categorical variables to numerical values
data['Gender'] = data['Gender'].astype('category').cat.codes
data['Country'] = data['Country'].astype('category').cat.codes
data['MentalHealthConsequence'] = data['MentalHealthConsequence'].astype('category').cat.codes
data['SeekTreatment'] = data['SeekTreatment'].astype('category').cat.codes

# Split the data into training and testing sets
X = data[['Age', 'Gender', 'Country', 'MentalHealthConsequence']]
y = data['SeekTreatment']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the Random Forest Classifier
clf = RandomForestClassifier()
clf.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = clf.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Create a confusion matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(confusion_matrix)

Accuracy: 0.43253968253968256
Confusion Matrix:
[[20 41 17]
 [36 81 14]
 [16 19  8]]


In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load the dataset
data = pd.read_csv('saviour.csv')

# Split the dataset into features (X) and target variable (y)
y = data['SeekTreatment']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Random Forest Classifier
clf = RandomForestClassifier()
clf.fit(X_train, y_train)

# Add the predicted values to the original DataFrame
data['PredictedTreatmentSeeking'] = clf.predict(X)

# Print the accuracy of the model
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

KeyError: ignored

In [ ]:
import pandas as pd
import numpy as np
df  =pd.read_csv('saviour1.csv')
df.dtypes

Timestamp                  object
Age                         int64
Gender                     object
Country                    object
State                      object
self_employed              object
family_history             object
treatment                  object
work_interfere             object
no_employees               object
remote_work                object
remote_work.1              object
benefits                   object
CareOptions                object
WellnessProgram            object
SeekTreatment              object
Anonymity                  object
Leave                      object
MentalHealthConsequence    object
PhysHealthConsequence      object
Coworkers                  object
Supervisor                 object
MentalHealthInterview      object
PhysHealthInterview        object
MentalVsPhysical           object
ObservedConsequence        object
comments                   object
dtype: object

yeh tune kya kiya